### ISSUE TITLE
x64 version for AviSynth+?

### ISSUE THREAD

**Issue by Reel-Deal** [ItEndsWithTens/TurnsTile#1]
Hi Rob,

Any hope for a 64-bit version for AviSynth+?

**Comment by ItEndsWithTens** [comment]
Oh, damn, I only realize now I never bothered updating my old plugins for x64 (or the new color spaces), yikes. Shouldn't be too much work, and this thing could stand to be updated anyway. I'll get on it ASAP, thanks for the nudge!

**Comment by Reel-Deal** [comment]
No worries, thank you for you plugins :)

**Comment by ItEndsWithTens** [comment]
Okay, a little progress! I'm not done yet, but I've now got a simple CI workflow set up, so if you [follow this link](https://dev.azure.com/robertmartens0491/TurnsTile/_build/results?buildId=96&view=artifacts&type=publishedArtifacts) you should be able to see the top level artifact that was most recently built.

If you hover over "TurnsTile binaries" and click the three dots on the right, you can download a zip file with my two actual distribution zips inside; sorry it's so clumsy for now, but this isn't an actual "release", per se. Once I get a process in place for drafting Github releases from tags this'll be more user friendly.

In the meantime you can at least see if the plugin's existing features work. There's nothing new, no new color spaces, the readme isn't updated, the 'extras' directory isn't in the .zip, the version number's still outdated, all sorts of issues I'll have to fix, but there are x86 and x64 versions of the DLL, both built with the 3.6.1 header, so the barebones goal of "64-bit version for AviSynth+" is accomplished. Now I just need to spruce it up a bit and get a real release posted!

**Comment by ItEndsWithTens** [comment]
Okay, there you have it, [version 1.0.0](https://github.com/ItEndsWithTens/TurnsTile/releases/tag/v1.0.0) is now available! No new colorspaces, VS support, or other features to speak of, but the plugin's been reworked to target Avisynth+, and binaries have been posted for Win32, Win64, Linux, and macOS.

Hopefully the availability of a 64-bit build is enough to get you started; high bit depth stuff is not something I've done too much with, so it'll take me a bit to sort out the new colorspaces, but I'll get there sooner or later.

**Comment by Reel-Deal** [comment]
Hi Rob,

Thank you very much for taking time to update the plugin. I apologize for the late response, I've been away for for sometime. I finally have time to test it, I will let you know if I find anything out of the norm. Thanks again!
